/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// CreateNodesSingleCephInitRequest
    /// </summary>
    [DataContract(Name = "CreateNodesSingleCephInitRequest")]
    public partial class CreateNodesSingleCephInitRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNodesSingleCephInitRequest" /> class.
        /// </summary>
        /// <param name="clusterNetwork">clusterNetwork.</param>
        /// <param name="disableCephx">disableCephx.</param>
        /// <param name="minSize">minSize.</param>
        /// <param name="network">network.</param>
        /// <param name="pgBits">pgBits.</param>
        /// <param name="size">size.</param>
        public CreateNodesSingleCephInitRequest(string clusterNetwork = default(string), bool disableCephx = default(bool), int minSize = default(int), string network = default(string), int pgBits = default(int), int size = default(int))
        {
            this.ClusterNetwork = clusterNetwork;
            this.DisableCephx = disableCephx;
            this.MinSize = minSize;
            this.Network = network;
            this.PgBits = pgBits;
            this.Size = size;
        }

        /// <summary>
        /// Gets or Sets ClusterNetwork
        /// </summary>
        [DataMember(Name = "cluster-network", EmitDefaultValue = false)]
        public string ClusterNetwork { get; set; }

        /// <summary>
        /// Gets or Sets DisableCephx
        /// </summary>
        [DataMember(Name = "disable_cephx", EmitDefaultValue = true)]
        public bool DisableCephx { get; set; }

        /// <summary>
        /// Gets or Sets MinSize
        /// </summary>
        [DataMember(Name = "min_size", EmitDefaultValue = false)]
        public int MinSize { get; set; }

        /// <summary>
        /// Gets or Sets Network
        /// </summary>
        [DataMember(Name = "network", EmitDefaultValue = false)]
        public string Network { get; set; }

        /// <summary>
        /// Gets or Sets PgBits
        /// </summary>
        [DataMember(Name = "pg_bits", EmitDefaultValue = false)]
        public int PgBits { get; set; }

        /// <summary>
        /// Gets or Sets Size
        /// </summary>
        [DataMember(Name = "size", EmitDefaultValue = false)]
        public int Size { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateNodesSingleCephInitRequest {\n");
            sb.Append("  ClusterNetwork: ").Append(ClusterNetwork).Append("\n");
            sb.Append("  DisableCephx: ").Append(DisableCephx).Append("\n");
            sb.Append("  MinSize: ").Append(MinSize).Append("\n");
            sb.Append("  Network: ").Append(Network).Append("\n");
            sb.Append("  PgBits: ").Append(PgBits).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
