/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// CreateNodesSingleDisksLvmthinRequest
    /// </summary>
    [DataContract(Name = "CreateNodesSingleDisksLvmthinRequest")]
    public partial class CreateNodesSingleDisksLvmthinRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNodesSingleDisksLvmthinRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateNodesSingleDisksLvmthinRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNodesSingleDisksLvmthinRequest" /> class.
        /// </summary>
        /// <param name="addStorage">addStorage.</param>
        /// <param name="device">device (required).</param>
        /// <param name="name">name (required).</param>
        public CreateNodesSingleDisksLvmthinRequest(bool addStorage = default(bool), string device = default(string), string name = default(string))
        {
            // to ensure "device" is required (not null)
            if (device == null)
            {
                throw new ArgumentNullException("device is a required property for CreateNodesSingleDisksLvmthinRequest and cannot be null");
            }
            this.Device = device;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateNodesSingleDisksLvmthinRequest and cannot be null");
            }
            this.Name = name;
            this.AddStorage = addStorage;
        }

        /// <summary>
        /// Gets or Sets AddStorage
        /// </summary>
        [DataMember(Name = "add_storage", EmitDefaultValue = true)]
        public bool AddStorage { get; set; }

        /// <summary>
        /// Gets or Sets Device
        /// </summary>
        [DataMember(Name = "device", IsRequired = true, EmitDefaultValue = true)]
        public string Device { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateNodesSingleDisksLvmthinRequest {\n");
            sb.Append("  AddStorage: ").Append(AddStorage).Append("\n");
            sb.Append("  Device: ").Append(Device).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
