/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// CreateClusterSdnDnsRequest
    /// </summary>
    [DataContract(Name = "CreateClusterSdnDnsRequest")]
    public partial class CreateClusterSdnDnsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateClusterSdnDnsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateClusterSdnDnsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateClusterSdnDnsRequest" /> class.
        /// </summary>
        /// <param name="dns">dns (required).</param>
        /// <param name="fingerprint">fingerprint.</param>
        /// <param name="key">key (required).</param>
        /// <param name="lockToken">lockToken.</param>
        /// <param name="reversemaskv6">reversemaskv6.</param>
        /// <param name="reversev6mask">reversev6mask.</param>
        /// <param name="ttl">ttl.</param>
        /// <param name="type">type (required).</param>
        /// <param name="url">url (required).</param>
        public CreateClusterSdnDnsRequest(string dns = default(string), string fingerprint = default(string), string key = default(string), string lockToken = default(string), int reversemaskv6 = default(int), int reversev6mask = default(int), int ttl = default(int), string type = default(string), string url = default(string))
        {
            // to ensure "dns" is required (not null)
            if (dns == null)
            {
                throw new ArgumentNullException("dns is a required property for CreateClusterSdnDnsRequest and cannot be null");
            }
            this.Dns = dns;
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for CreateClusterSdnDnsRequest and cannot be null");
            }
            this.Key = key;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for CreateClusterSdnDnsRequest and cannot be null");
            }
            this.Type = type;
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for CreateClusterSdnDnsRequest and cannot be null");
            }
            this.Url = url;
            this.Fingerprint = fingerprint;
            this.LockToken = lockToken;
            this.Reversemaskv6 = reversemaskv6;
            this.Reversev6mask = reversev6mask;
            this.Ttl = ttl;
        }

        /// <summary>
        /// Gets or Sets Dns
        /// </summary>
        [DataMember(Name = "dns", IsRequired = true, EmitDefaultValue = true)]
        public string Dns { get; set; }

        /// <summary>
        /// Gets or Sets Fingerprint
        /// </summary>
        [DataMember(Name = "fingerprint", EmitDefaultValue = false)]
        public string Fingerprint { get; set; }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Gets or Sets LockToken
        /// </summary>
        [DataMember(Name = "lock-token", EmitDefaultValue = false)]
        public string LockToken { get; set; }

        /// <summary>
        /// Gets or Sets Reversemaskv6
        /// </summary>
        [DataMember(Name = "reversemaskv6", EmitDefaultValue = false)]
        public int Reversemaskv6 { get; set; }

        /// <summary>
        /// Gets or Sets Reversev6mask
        /// </summary>
        [DataMember(Name = "reversev6mask", EmitDefaultValue = false)]
        public int Reversev6mask { get; set; }

        /// <summary>
        /// Gets or Sets Ttl
        /// </summary>
        [DataMember(Name = "ttl", EmitDefaultValue = false)]
        public int Ttl { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateClusterSdnDnsRequest {\n");
            sb.Append("  Dns: ").Append(Dns).Append("\n");
            sb.Append("  Fingerprint: ").Append(Fingerprint).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  LockToken: ").Append(LockToken).Append("\n");
            sb.Append("  Reversemaskv6: ").Append(Reversemaskv6).Append("\n");
            sb.Append("  Reversev6mask: ").Append(Reversev6mask).Append("\n");
            sb.Append("  Ttl: ").Append(Ttl).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
