/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// CreateNodesSingleCephOsdRequest
    /// </summary>
    [DataContract(Name = "CreateNodesSingleCephOsdRequest")]
    public partial class CreateNodesSingleCephOsdRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNodesSingleCephOsdRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateNodesSingleCephOsdRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNodesSingleCephOsdRequest" /> class.
        /// </summary>
        /// <param name="crushDeviceClass">crushDeviceClass.</param>
        /// <param name="dbDev">dbDev.</param>
        /// <param name="dbDevSize">dbDevSize.</param>
        /// <param name="dev">dev (required).</param>
        /// <param name="encrypted">encrypted.</param>
        /// <param name="osdsPerDevice">osdsPerDevice.</param>
        /// <param name="walDev">walDev.</param>
        /// <param name="walDevSize">walDevSize.</param>
        public CreateNodesSingleCephOsdRequest(string crushDeviceClass = default(string), string dbDev = default(string), decimal dbDevSize = default(decimal), string dev = default(string), bool encrypted = default(bool), int osdsPerDevice = default(int), string walDev = default(string), decimal walDevSize = default(decimal))
        {
            // to ensure "dev" is required (not null)
            if (dev == null)
            {
                throw new ArgumentNullException("dev is a required property for CreateNodesSingleCephOsdRequest and cannot be null");
            }
            this.Dev = dev;
            this.CrushDeviceClass = crushDeviceClass;
            this.DbDev = dbDev;
            this.DbDevSize = dbDevSize;
            this.Encrypted = encrypted;
            this.OsdsPerDevice = osdsPerDevice;
            this.WalDev = walDev;
            this.WalDevSize = walDevSize;
        }

        /// <summary>
        /// Gets or Sets CrushDeviceClass
        /// </summary>
        [DataMember(Name = "crush-device-class", EmitDefaultValue = false)]
        public string CrushDeviceClass { get; set; }

        /// <summary>
        /// Gets or Sets DbDev
        /// </summary>
        [DataMember(Name = "db_dev", EmitDefaultValue = false)]
        public string DbDev { get; set; }

        /// <summary>
        /// Gets or Sets DbDevSize
        /// </summary>
        [DataMember(Name = "db_dev_size", EmitDefaultValue = false)]
        public decimal DbDevSize { get; set; }

        /// <summary>
        /// Gets or Sets Dev
        /// </summary>
        [DataMember(Name = "dev", IsRequired = true, EmitDefaultValue = true)]
        public string Dev { get; set; }

        /// <summary>
        /// Gets or Sets Encrypted
        /// </summary>
        [DataMember(Name = "encrypted", EmitDefaultValue = true)]
        public bool Encrypted { get; set; }

        /// <summary>
        /// Gets or Sets OsdsPerDevice
        /// </summary>
        [DataMember(Name = "osds-per-device", EmitDefaultValue = false)]
        public int OsdsPerDevice { get; set; }

        /// <summary>
        /// Gets or Sets WalDev
        /// </summary>
        [DataMember(Name = "wal_dev", EmitDefaultValue = false)]
        public string WalDev { get; set; }

        /// <summary>
        /// Gets or Sets WalDevSize
        /// </summary>
        [DataMember(Name = "wal_dev_size", EmitDefaultValue = false)]
        public decimal WalDevSize { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateNodesSingleCephOsdRequest {\n");
            sb.Append("  CrushDeviceClass: ").Append(CrushDeviceClass).Append("\n");
            sb.Append("  DbDev: ").Append(DbDev).Append("\n");
            sb.Append("  DbDevSize: ").Append(DbDevSize).Append("\n");
            sb.Append("  Dev: ").Append(Dev).Append("\n");
            sb.Append("  Encrypted: ").Append(Encrypted).Append("\n");
            sb.Append("  OsdsPerDevice: ").Append(OsdsPerDevice).Append("\n");
            sb.Append("  WalDev: ").Append(WalDev).Append("\n");
            sb.Append("  WalDevSize: ").Append(WalDevSize).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
