/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// CreateClusterSDNControllerRequest
    /// </summary>
    [DataContract(Name = "CreateClusterSDNControllerRequest")]
    public partial class CreateClusterSDNControllerRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateClusterSDNControllerRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateClusterSDNControllerRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateClusterSDNControllerRequest" /> class.
        /// </summary>
        /// <param name="asn">asn.</param>
        /// <param name="bgpMultipathAsPathRelax">bgpMultipathAsPathRelax.</param>
        /// <param name="controller">controller (required).</param>
        /// <param name="ebgp">ebgp.</param>
        /// <param name="ebgpMultihop">ebgpMultihop.</param>
        /// <param name="fabric">fabric.</param>
        /// <param name="isisDomain">isisDomain.</param>
        /// <param name="isisIfaces">isisIfaces.</param>
        /// <param name="isisNet">isisNet.</param>
        /// <param name="lockToken">lockToken.</param>
        /// <param name="loopback">loopback.</param>
        /// <param name="node">node.</param>
        /// <param name="peers">peers.</param>
        /// <param name="type">type (required).</param>
        public CreateClusterSDNControllerRequest(int asn = default(int), bool bgpMultipathAsPathRelax = default(bool), string controller = default(string), bool ebgp = default(bool), int ebgpMultihop = default(int), string fabric = default(string), string isisDomain = default(string), string isisIfaces = default(string), string isisNet = default(string), string lockToken = default(string), string loopback = default(string), string node = default(string), string peers = default(string), string type = default(string))
        {
            // to ensure "controller" is required (not null)
            if (controller == null)
            {
                throw new ArgumentNullException("controller is a required property for CreateClusterSDNControllerRequest and cannot be null");
            }
            this.Controller = controller;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for CreateClusterSDNControllerRequest and cannot be null");
            }
            this.Type = type;
            this.Asn = asn;
            this.BgpMultipathAsPathRelax = bgpMultipathAsPathRelax;
            this.Ebgp = ebgp;
            this.EbgpMultihop = ebgpMultihop;
            this.Fabric = fabric;
            this.IsisDomain = isisDomain;
            this.IsisIfaces = isisIfaces;
            this.IsisNet = isisNet;
            this.LockToken = lockToken;
            this.Loopback = loopback;
            this.Node = node;
            this.Peers = peers;
        }

        /// <summary>
        /// Gets or Sets Asn
        /// </summary>
        [DataMember(Name = "asn", EmitDefaultValue = false)]
        public int Asn { get; set; }

        /// <summary>
        /// Gets or Sets BgpMultipathAsPathRelax
        /// </summary>
        [DataMember(Name = "bgp-multipath-as-path-relax", EmitDefaultValue = true)]
        public bool BgpMultipathAsPathRelax { get; set; }

        /// <summary>
        /// Gets or Sets Controller
        /// </summary>
        [DataMember(Name = "controller", IsRequired = true, EmitDefaultValue = true)]
        public string Controller { get; set; }

        /// <summary>
        /// Gets or Sets Ebgp
        /// </summary>
        [DataMember(Name = "ebgp", EmitDefaultValue = true)]
        public bool Ebgp { get; set; }

        /// <summary>
        /// Gets or Sets EbgpMultihop
        /// </summary>
        [DataMember(Name = "ebgp-multihop", EmitDefaultValue = false)]
        public int EbgpMultihop { get; set; }

        /// <summary>
        /// Gets or Sets Fabric
        /// </summary>
        [DataMember(Name = "fabric", EmitDefaultValue = false)]
        public string Fabric { get; set; }

        /// <summary>
        /// Gets or Sets IsisDomain
        /// </summary>
        [DataMember(Name = "isis-domain", EmitDefaultValue = false)]
        public string IsisDomain { get; set; }

        /// <summary>
        /// Gets or Sets IsisIfaces
        /// </summary>
        [DataMember(Name = "isis-ifaces", EmitDefaultValue = false)]
        public string IsisIfaces { get; set; }

        /// <summary>
        /// Gets or Sets IsisNet
        /// </summary>
        [DataMember(Name = "isis-net", EmitDefaultValue = false)]
        public string IsisNet { get; set; }

        /// <summary>
        /// Gets or Sets LockToken
        /// </summary>
        [DataMember(Name = "lock-token", EmitDefaultValue = false)]
        public string LockToken { get; set; }

        /// <summary>
        /// Gets or Sets Loopback
        /// </summary>
        [DataMember(Name = "loopback", EmitDefaultValue = false)]
        public string Loopback { get; set; }

        /// <summary>
        /// Gets or Sets Node
        /// </summary>
        [DataMember(Name = "node", EmitDefaultValue = false)]
        public string Node { get; set; }

        /// <summary>
        /// Gets or Sets Peers
        /// </summary>
        [DataMember(Name = "peers", EmitDefaultValue = false)]
        public string Peers { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateClusterSDNControllerRequest {\n");
            sb.Append("  Asn: ").Append(Asn).Append("\n");
            sb.Append("  BgpMultipathAsPathRelax: ").Append(BgpMultipathAsPathRelax).Append("\n");
            sb.Append("  Controller: ").Append(Controller).Append("\n");
            sb.Append("  Ebgp: ").Append(Ebgp).Append("\n");
            sb.Append("  EbgpMultihop: ").Append(EbgpMultihop).Append("\n");
            sb.Append("  Fabric: ").Append(Fabric).Append("\n");
            sb.Append("  IsisDomain: ").Append(IsisDomain).Append("\n");
            sb.Append("  IsisIfaces: ").Append(IsisIfaces).Append("\n");
            sb.Append("  IsisNet: ").Append(IsisNet).Append("\n");
            sb.Append("  LockToken: ").Append(LockToken).Append("\n");
            sb.Append("  Loopback: ").Append(Loopback).Append("\n");
            sb.Append("  Node: ").Append(Node).Append("\n");
            sb.Append("  Peers: ").Append(Peers).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
