/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// CreateStorage200ResponseData
    /// </summary>
    [DataContract(Name = "createStorage_200_response_data")]
    public partial class CreateStorage200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateStorage200ResponseData" /> class.
        /// </summary>
        /// <param name="config">config.</param>
        /// <param name="storage">The ID of the created storage..</param>
        /// <param name="type">The type of the created storage..</param>
        public CreateStorage200ResponseData(CreateStorage200ResponseDataConfig config = default(CreateStorage200ResponseDataConfig), string storage = default(string), string type = default(string))
        {
            this.Config = config;
            this.Storage = storage;
            this.Type = type;
        }

        /// <summary>
        /// Gets or Sets Config
        /// </summary>
        [DataMember(Name = "config", EmitDefaultValue = false)]
        public CreateStorage200ResponseDataConfig Config { get; set; }

        /// <summary>
        /// The ID of the created storage.
        /// </summary>
        /// <value>The ID of the created storage.</value>
        [DataMember(Name = "storage", EmitDefaultValue = false)]
        public string Storage { get; set; }

        /// <summary>
        /// The type of the created storage.
        /// </summary>
        /// <value>The type of the created storage.</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateStorage200ResponseData {\n");
            sb.Append("  Config: ").Append(Config).Append("\n");
            sb.Append("  Storage: ").Append(Storage).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
