/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// CreateAccessVncticketRequest
    /// </summary>
    [DataContract(Name = "CreateAccessVncticketRequest")]
    public partial class CreateAccessVncticketRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAccessVncticketRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateAccessVncticketRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAccessVncticketRequest" /> class.
        /// </summary>
        /// <param name="authid">authid (required).</param>
        /// <param name="path">path (required).</param>
        /// <param name="privs">privs (required).</param>
        /// <param name="vncticket">vncticket (required).</param>
        public CreateAccessVncticketRequest(string authid = default(string), string path = default(string), string privs = default(string), string vncticket = default(string))
        {
            // to ensure "authid" is required (not null)
            if (authid == null)
            {
                throw new ArgumentNullException("authid is a required property for CreateAccessVncticketRequest and cannot be null");
            }
            this.Authid = authid;
            // to ensure "path" is required (not null)
            if (path == null)
            {
                throw new ArgumentNullException("path is a required property for CreateAccessVncticketRequest and cannot be null");
            }
            this.Path = path;
            // to ensure "privs" is required (not null)
            if (privs == null)
            {
                throw new ArgumentNullException("privs is a required property for CreateAccessVncticketRequest and cannot be null");
            }
            this.Privs = privs;
            // to ensure "vncticket" is required (not null)
            if (vncticket == null)
            {
                throw new ArgumentNullException("vncticket is a required property for CreateAccessVncticketRequest and cannot be null");
            }
            this.Vncticket = vncticket;
        }

        /// <summary>
        /// Gets or Sets Authid
        /// </summary>
        [DataMember(Name = "authid", IsRequired = true, EmitDefaultValue = true)]
        public string Authid { get; set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [DataMember(Name = "path", IsRequired = true, EmitDefaultValue = true)]
        public string Path { get; set; }

        /// <summary>
        /// Gets or Sets Privs
        /// </summary>
        [DataMember(Name = "privs", IsRequired = true, EmitDefaultValue = true)]
        public string Privs { get; set; }

        /// <summary>
        /// Gets or Sets Vncticket
        /// </summary>
        [DataMember(Name = "vncticket", IsRequired = true, EmitDefaultValue = true)]
        public string Vncticket { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateAccessVncticketRequest {\n");
            sb.Append("  Authid: ").Append(Authid).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  Privs: ").Append(Privs).Append("\n");
            sb.Append("  Vncticket: ").Append(Vncticket).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
