/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// CreateNodesSingleLxcSingleStatusStopRequest
    /// </summary>
    [DataContract(Name = "CreateNodesSingleLxcSingleStatusStopRequest")]
    public partial class CreateNodesSingleLxcSingleStatusStopRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNodesSingleLxcSingleStatusStopRequest" /> class.
        /// </summary>
        /// <param name="overruleShutdown">overruleShutdown.</param>
        /// <param name="skiplock">skiplock.</param>
        public CreateNodesSingleLxcSingleStatusStopRequest(bool overruleShutdown = default(bool), bool skiplock = default(bool))
        {
            this.OverruleShutdown = overruleShutdown;
            this.Skiplock = skiplock;
        }

        /// <summary>
        /// Gets or Sets OverruleShutdown
        /// </summary>
        [DataMember(Name = "overrule-shutdown", EmitDefaultValue = true)]
        public bool OverruleShutdown { get; set; }

        /// <summary>
        /// Gets or Sets Skiplock
        /// </summary>
        [DataMember(Name = "skiplock", EmitDefaultValue = true)]
        public bool Skiplock { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateNodesSingleLxcSingleStatusStopRequest {\n");
            sb.Append("  OverruleShutdown: ").Append(OverruleShutdown).Append("\n");
            sb.Append("  Skiplock: ").Append(Skiplock).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
