/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// CreateNodesSingleQemuSingleMovediskRequest
    /// </summary>
    [DataContract(Name = "CreateNodesSingleQemuSingleMovediskRequest")]
    public partial class CreateNodesSingleQemuSingleMovediskRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNodesSingleQemuSingleMovediskRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateNodesSingleQemuSingleMovediskRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNodesSingleQemuSingleMovediskRequest" /> class.
        /// </summary>
        /// <param name="bwlimit">bwlimit.</param>
        /// <param name="delete">delete.</param>
        /// <param name="digest">digest.</param>
        /// <param name="disk">disk (required).</param>
        /// <param name="format">format.</param>
        /// <param name="storage">storage.</param>
        /// <param name="targetDigest">targetDigest.</param>
        /// <param name="targetDisk">targetDisk.</param>
        /// <param name="targetVmid">targetVmid.</param>
        public CreateNodesSingleQemuSingleMovediskRequest(int bwlimit = default(int), bool delete = default(bool), string digest = default(string), string disk = default(string), string format = default(string), string storage = default(string), string targetDigest = default(string), string targetDisk = default(string), int targetVmid = default(int))
        {
            // to ensure "disk" is required (not null)
            if (disk == null)
            {
                throw new ArgumentNullException("disk is a required property for CreateNodesSingleQemuSingleMovediskRequest and cannot be null");
            }
            this.Disk = disk;
            this.Bwlimit = bwlimit;
            this.Delete = delete;
            this.Digest = digest;
            this.Format = format;
            this.Storage = storage;
            this.TargetDigest = targetDigest;
            this.TargetDisk = targetDisk;
            this.TargetVmid = targetVmid;
        }

        /// <summary>
        /// Gets or Sets Bwlimit
        /// </summary>
        [DataMember(Name = "bwlimit", EmitDefaultValue = false)]
        public int Bwlimit { get; set; }

        /// <summary>
        /// Gets or Sets Delete
        /// </summary>
        [DataMember(Name = "delete", EmitDefaultValue = true)]
        public bool Delete { get; set; }

        /// <summary>
        /// Gets or Sets Digest
        /// </summary>
        [DataMember(Name = "digest", EmitDefaultValue = false)]
        public string Digest { get; set; }

        /// <summary>
        /// Gets or Sets Disk
        /// </summary>
        [DataMember(Name = "disk", IsRequired = true, EmitDefaultValue = true)]
        public string Disk { get; set; }

        /// <summary>
        /// Gets or Sets Format
        /// </summary>
        [DataMember(Name = "format", EmitDefaultValue = false)]
        public string Format { get; set; }

        /// <summary>
        /// Gets or Sets Storage
        /// </summary>
        [DataMember(Name = "storage", EmitDefaultValue = false)]
        public string Storage { get; set; }

        /// <summary>
        /// Gets or Sets TargetDigest
        /// </summary>
        [DataMember(Name = "target-digest", EmitDefaultValue = false)]
        public string TargetDigest { get; set; }

        /// <summary>
        /// Gets or Sets TargetDisk
        /// </summary>
        [DataMember(Name = "target-disk", EmitDefaultValue = false)]
        public string TargetDisk { get; set; }

        /// <summary>
        /// Gets or Sets TargetVmid
        /// </summary>
        [DataMember(Name = "target-vmid", EmitDefaultValue = false)]
        public int TargetVmid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateNodesSingleQemuSingleMovediskRequest {\n");
            sb.Append("  Bwlimit: ").Append(Bwlimit).Append("\n");
            sb.Append("  Delete: ").Append(Delete).Append("\n");
            sb.Append("  Digest: ").Append(Digest).Append("\n");
            sb.Append("  Disk: ").Append(Disk).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  Storage: ").Append(Storage).Append("\n");
            sb.Append("  TargetDigest: ").Append(TargetDigest).Append("\n");
            sb.Append("  TargetDisk: ").Append(TargetDisk).Append("\n");
            sb.Append("  TargetVmid: ").Append(TargetVmid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
