/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// CreateClusterHaResourcesSingleRelocate200ResponseData
    /// </summary>
    [DataContract(Name = "createClusterHaResourcesSingleRelocate_200_response_data")]
    public partial class CreateClusterHaResourcesSingleRelocate200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateClusterHaResourcesSingleRelocate200ResponseData" /> class.
        /// </summary>
        /// <param name="blockingResources">HA resources, which are blocking the given HA resource from being relocated to the requested target node..</param>
        /// <param name="comigratedResources">HA resources, which are relocated to the same requested target node as the given HA resource, because these are in positive affinity with the HA resource..</param>
        /// <param name="requestedNode">Node, which was requested to be relocated to..</param>
        /// <param name="sid">HA resource, which is requested to be relocated..</param>
        public CreateClusterHaResourcesSingleRelocate200ResponseData(List<CreateClusterHaResourcesSingleRelocate200ResponseDataBlockingResourcesInner> blockingResources = default(List<CreateClusterHaResourcesSingleRelocate200ResponseDataBlockingResourcesInner>), List<string> comigratedResources = default(List<string>), string requestedNode = default(string), string sid = default(string))
        {
            this.BlockingResources = blockingResources;
            this.ComigratedResources = comigratedResources;
            this.RequestedNode = requestedNode;
            this.Sid = sid;
        }

        /// <summary>
        /// HA resources, which are blocking the given HA resource from being relocated to the requested target node.
        /// </summary>
        /// <value>HA resources, which are blocking the given HA resource from being relocated to the requested target node.</value>
        [DataMember(Name = "blocking-resources", EmitDefaultValue = false)]
        public List<CreateClusterHaResourcesSingleRelocate200ResponseDataBlockingResourcesInner> BlockingResources { get; set; }

        /// <summary>
        /// HA resources, which are relocated to the same requested target node as the given HA resource, because these are in positive affinity with the HA resource.
        /// </summary>
        /// <value>HA resources, which are relocated to the same requested target node as the given HA resource, because these are in positive affinity with the HA resource.</value>
        [DataMember(Name = "comigrated-resources", EmitDefaultValue = false)]
        public List<string> ComigratedResources { get; set; }

        /// <summary>
        /// Node, which was requested to be relocated to.
        /// </summary>
        /// <value>Node, which was requested to be relocated to.</value>
        [DataMember(Name = "requested-node", EmitDefaultValue = false)]
        public string RequestedNode { get; set; }

        /// <summary>
        /// HA resource, which is requested to be relocated.
        /// </summary>
        /// <value>HA resource, which is requested to be relocated.</value>
        [DataMember(Name = "sid", EmitDefaultValue = false)]
        public string Sid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateClusterHaResourcesSingleRelocate200ResponseData {\n");
            sb.Append("  BlockingResources: ").Append(BlockingResources).Append("\n");
            sb.Append("  ComigratedResources: ").Append(ComigratedResources).Append("\n");
            sb.Append("  RequestedNode: ").Append(RequestedNode).Append("\n");
            sb.Append("  Sid: ").Append(Sid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
