/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// CreateNodesSingleQemuSingleFirewallAliasesRequest
    /// </summary>
    [DataContract(Name = "CreateNodesSingleQemuSingleFirewallAliasesRequest")]
    public partial class CreateNodesSingleQemuSingleFirewallAliasesRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNodesSingleQemuSingleFirewallAliasesRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateNodesSingleQemuSingleFirewallAliasesRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNodesSingleQemuSingleFirewallAliasesRequest" /> class.
        /// </summary>
        /// <param name="cidr">cidr (required).</param>
        /// <param name="comment">comment.</param>
        /// <param name="name">name (required).</param>
        public CreateNodesSingleQemuSingleFirewallAliasesRequest(string cidr = default(string), string comment = default(string), string name = default(string))
        {
            // to ensure "cidr" is required (not null)
            if (cidr == null)
            {
                throw new ArgumentNullException("cidr is a required property for CreateNodesSingleQemuSingleFirewallAliasesRequest and cannot be null");
            }
            this.Cidr = cidr;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateNodesSingleQemuSingleFirewallAliasesRequest and cannot be null");
            }
            this.Name = name;
            this.Comment = comment;
        }

        /// <summary>
        /// Gets or Sets Cidr
        /// </summary>
        [DataMember(Name = "cidr", IsRequired = true, EmitDefaultValue = true)]
        public string Cidr { get; set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [DataMember(Name = "comment", EmitDefaultValue = false)]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateNodesSingleQemuSingleFirewallAliasesRequest {\n");
            sb.Append("  Cidr: ").Append(Cidr).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
