/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// CreateNodesSingleLxcSingleCloneRequest
    /// </summary>
    [DataContract(Name = "CreateNodesSingleLxcSingleCloneRequest")]
    public partial class CreateNodesSingleLxcSingleCloneRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNodesSingleLxcSingleCloneRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateNodesSingleLxcSingleCloneRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNodesSingleLxcSingleCloneRequest" /> class.
        /// </summary>
        /// <param name="bwlimit">bwlimit.</param>
        /// <param name="description">description.</param>
        /// <param name="full">full.</param>
        /// <param name="hostname">hostname.</param>
        /// <param name="newid">newid (required).</param>
        /// <param name="pool">pool.</param>
        /// <param name="snapname">snapname.</param>
        /// <param name="storage">storage.</param>
        /// <param name="target">target.</param>
        public CreateNodesSingleLxcSingleCloneRequest(decimal bwlimit = default(decimal), string description = default(string), bool full = default(bool), string hostname = default(string), int newid = default(int), string pool = default(string), string snapname = default(string), string storage = default(string), string target = default(string))
        {
            this.Newid = newid;
            this.Bwlimit = bwlimit;
            this.Description = description;
            this.Full = full;
            this.Hostname = hostname;
            this.Pool = pool;
            this.Snapname = snapname;
            this.Storage = storage;
            this.Target = target;
        }

        /// <summary>
        /// Gets or Sets Bwlimit
        /// </summary>
        [DataMember(Name = "bwlimit", EmitDefaultValue = false)]
        public decimal Bwlimit { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Full
        /// </summary>
        [DataMember(Name = "full", EmitDefaultValue = true)]
        public bool Full { get; set; }

        /// <summary>
        /// Gets or Sets Hostname
        /// </summary>
        [DataMember(Name = "hostname", EmitDefaultValue = false)]
        public string Hostname { get; set; }

        /// <summary>
        /// Gets or Sets Newid
        /// </summary>
        [DataMember(Name = "newid", IsRequired = true, EmitDefaultValue = true)]
        public int Newid { get; set; }

        /// <summary>
        /// Gets or Sets Pool
        /// </summary>
        [DataMember(Name = "pool", EmitDefaultValue = false)]
        public string Pool { get; set; }

        /// <summary>
        /// Gets or Sets Snapname
        /// </summary>
        [DataMember(Name = "snapname", EmitDefaultValue = false)]
        public string Snapname { get; set; }

        /// <summary>
        /// Gets or Sets Storage
        /// </summary>
        [DataMember(Name = "storage", EmitDefaultValue = false)]
        public string Storage { get; set; }

        /// <summary>
        /// Gets or Sets Target
        /// </summary>
        [DataMember(Name = "target", EmitDefaultValue = false)]
        public string Target { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateNodesSingleLxcSingleCloneRequest {\n");
            sb.Append("  Bwlimit: ").Append(Bwlimit).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Full: ").Append(Full).Append("\n");
            sb.Append("  Hostname: ").Append(Hostname).Append("\n");
            sb.Append("  Newid: ").Append(Newid).Append("\n");
            sb.Append("  Pool: ").Append(Pool).Append("\n");
            sb.Append("  Snapname: ").Append(Snapname).Append("\n");
            sb.Append("  Storage: ").Append(Storage).Append("\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
