/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// CreateNodesSingleTermproxyRequest
    /// </summary>
    [DataContract(Name = "CreateNodesSingleTermproxyRequest")]
    public partial class CreateNodesSingleTermproxyRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNodesSingleTermproxyRequest" /> class.
        /// </summary>
        /// <param name="cmd">cmd.</param>
        /// <param name="cmdOpts">cmdOpts.</param>
        public CreateNodesSingleTermproxyRequest(string cmd = default(string), string cmdOpts = default(string))
        {
            this.Cmd = cmd;
            this.CmdOpts = cmdOpts;
        }

        /// <summary>
        /// Gets or Sets Cmd
        /// </summary>
        [DataMember(Name = "cmd", EmitDefaultValue = false)]
        public string Cmd { get; set; }

        /// <summary>
        /// Gets or Sets CmdOpts
        /// </summary>
        [DataMember(Name = "cmd-opts", EmitDefaultValue = false)]
        public string CmdOpts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateNodesSingleTermproxyRequest {\n");
            sb.Append("  Cmd: ").Append(Cmd).Append("\n");
            sb.Append("  CmdOpts: ").Append(CmdOpts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
