/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetAccessGroups200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getAccessGroups_200_response_data_inner")]
    public partial class GetAccessGroups200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAccessGroups200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="comment">comment.</param>
        /// <param name="groupid">groupid.</param>
        /// <param name="users">list of users which form this group.</param>
        public GetAccessGroups200ResponseDataInner(string comment = default(string), string groupid = default(string), string users = default(string))
        {
            this.Comment = comment;
            this.Groupid = groupid;
            this.Users = users;
        }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [DataMember(Name = "comment", EmitDefaultValue = false)]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or Sets Groupid
        /// </summary>
        [DataMember(Name = "groupid", EmitDefaultValue = false)]
        public string Groupid { get; set; }

        /// <summary>
        /// list of users which form this group
        /// </summary>
        /// <value>list of users which form this group</value>
        [DataMember(Name = "users", EmitDefaultValue = false)]
        public string Users { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetAccessGroups200ResponseDataInner {\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  Groupid: ").Append(Groupid).Append("\n");
            sb.Append("  Users: ").Append(Users).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
