/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetAccessUsersSingleTfa200ResponseData
    /// </summary>
    [DataContract(Name = "getAccessUsersSingleTfa_200_response_data")]
    public partial class GetAccessUsersSingleTfa200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAccessUsersSingleTfa200ResponseData" /> class.
        /// </summary>
        /// <param name="realm">The type of TFA the users realm has set, if any..</param>
        /// <param name="types">Array of the user configured TFA types, if any. Only available if &#39;multiple&#39; was not passed..</param>
        /// <param name="user">The type of TFA the user has set, if any. Only set if &#39;multiple&#39; was not passed..</param>
        public GetAccessUsersSingleTfa200ResponseData(string realm = default(string), List<string> types = default(List<string>), string user = default(string))
        {
            this.Realm = realm;
            this.Types = types;
            this.User = user;
        }

        /// <summary>
        /// The type of TFA the users realm has set, if any.
        /// </summary>
        /// <value>The type of TFA the users realm has set, if any.</value>
        [DataMember(Name = "realm", EmitDefaultValue = false)]
        public string Realm { get; set; }

        /// <summary>
        /// Array of the user configured TFA types, if any. Only available if &#39;multiple&#39; was not passed.
        /// </summary>
        /// <value>Array of the user configured TFA types, if any. Only available if &#39;multiple&#39; was not passed.</value>
        [DataMember(Name = "types", EmitDefaultValue = false)]
        public List<string> Types { get; set; }

        /// <summary>
        /// The type of TFA the user has set, if any. Only set if &#39;multiple&#39; was not passed.
        /// </summary>
        /// <value>The type of TFA the user has set, if any. Only set if &#39;multiple&#39; was not passed.</value>
        [DataMember(Name = "user", EmitDefaultValue = false)]
        public string User { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetAccessUsersSingleTfa200ResponseData {\n");
            sb.Append("  Realm: ").Append(Realm).Append("\n");
            sb.Append("  Types: ").Append(Types).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
