/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetAccessTfaSingle200Response
    /// </summary>
    [DataContract(Name = "getAccessTfaSingle_200_response")]
    public partial class GetAccessTfaSingle200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAccessTfaSingle200Response" /> class.
        /// </summary>
        /// <param name="errors">errors.</param>
        /// <param name="data">A list of the user&#39;s TFA entries..</param>
        public GetAccessTfaSingle200Response(List<string> errors = default(List<string>), List<GetAccessTfa200ResponseDataInnerEntriesInner> data = default(List<GetAccessTfa200ResponseDataInnerEntriesInner>))
        {
            this.Errors = errors;
            this.Data = data;
        }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public List<string> Errors { get; set; }

        /// <summary>
        /// A list of the user&#39;s TFA entries.
        /// </summary>
        /// <value>A list of the user&#39;s TFA entries.</value>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public List<GetAccessTfa200ResponseDataInnerEntriesInner> Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetAccessTfaSingle200Response {\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
