/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetClusterFirewallIPSet200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getClusterFirewallIPSet_200_response_data_inner")]
    public partial class GetClusterFirewallIPSet200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetClusterFirewallIPSet200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="cidr">cidr.</param>
        /// <param name="comment">comment.</param>
        /// <param name="digest">Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications..</param>
        /// <param name="nomatch">nomatch.</param>
        public GetClusterFirewallIPSet200ResponseDataInner(string cidr = default(string), string comment = default(string), string digest = default(string), Int64 nomatch = default(Int64))
        {
            this.Cidr = cidr;
            this.Comment = comment;
            this.Digest = digest;
            this.Nomatch = nomatch;
        }

        /// <summary>
        /// Gets or Sets Cidr
        /// </summary>
        [DataMember(Name = "cidr", EmitDefaultValue = false)]
        public string Cidr { get; set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [DataMember(Name = "comment", EmitDefaultValue = false)]
        public string Comment { get; set; }

        /// <summary>
        /// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
        /// </summary>
        /// <value>Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.</value>
        [DataMember(Name = "digest", EmitDefaultValue = false)]
        public string Digest { get; set; }

        /// <summary>
        /// Gets or Sets Nomatch
        /// </summary>
        [DataMember(Name = "nomatch", EmitDefaultValue = false)]
        public Int64 Nomatch { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetClusterFirewallIPSet200ResponseDataInner {\n");
            sb.Append("  Cidr: ").Append(Cidr).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  Digest: ").Append(Digest).Append("\n");
            sb.Append("  Nomatch: ").Append(Nomatch).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
