/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetClusterFirewallMacros200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getClusterFirewallMacros_200_response_data_inner")]
    public partial class GetClusterFirewallMacros200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetClusterFirewallMacros200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="descr">More verbose description (if available)..</param>
        /// <param name="macro">Macro name..</param>
        public GetClusterFirewallMacros200ResponseDataInner(string descr = default(string), string macro = default(string))
        {
            this.Descr = descr;
            this.Macro = macro;
        }

        /// <summary>
        /// More verbose description (if available).
        /// </summary>
        /// <value>More verbose description (if available).</value>
        [DataMember(Name = "descr", EmitDefaultValue = false)]
        public string Descr { get; set; }

        /// <summary>
        /// Macro name.
        /// </summary>
        /// <value>Macro name.</value>
        [DataMember(Name = "macro", EmitDefaultValue = false)]
        public string Macro { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetClusterFirewallMacros200ResponseDataInner {\n");
            sb.Append("  Descr: ").Append(Descr).Append("\n");
            sb.Append("  Macro: ").Append(Macro).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
