/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetClusterJobsScheduleanalyze200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getClusterJobsScheduleanalyze_200_response_data_inner")]
    public partial class GetClusterJobsScheduleanalyze200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetClusterJobsScheduleanalyze200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="timestamp">UNIX timestamp for the run..</param>
        /// <param name="utc">UTC timestamp for the run..</param>
        public GetClusterJobsScheduleanalyze200ResponseDataInner(Int64 timestamp = default(Int64), string utc = default(string))
        {
            this.Timestamp = timestamp;
            this.Utc = utc;
        }

        /// <summary>
        /// UNIX timestamp for the run.
        /// </summary>
        /// <value>UNIX timestamp for the run.</value>
        [DataMember(Name = "timestamp", EmitDefaultValue = false)]
        public Int64 Timestamp { get; set; }

        /// <summary>
        /// UTC timestamp for the run.
        /// </summary>
        /// <value>UTC timestamp for the run.</value>
        [DataMember(Name = "utc", EmitDefaultValue = false)]
        public string Utc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetClusterJobsScheduleanalyze200ResponseDataInner {\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Utc: ").Append(Utc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
