/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetClusterNotificationsEndpointsSmtp200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getClusterNotificationsEndpointsSmtp_200_response_data_inner")]
    public partial class GetClusterNotificationsEndpointsSmtp200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetClusterNotificationsEndpointsSmtp200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="author">Author of the mail. Defaults to &#39;Proxmox VE&#39;..</param>
        /// <param name="comment">Comment.</param>
        /// <param name="disable">Disable this target.</param>
        /// <param name="fromAddress">&#x60;From&#x60; address for the mail.</param>
        /// <param name="mailto">List of email recipients.</param>
        /// <param name="mailtoUser">List of users.</param>
        /// <param name="mode">Determine which encryption method shall be used for the connection..</param>
        /// <param name="name">The name of the endpoint..</param>
        /// <param name="origin">Show if this entry was created by a user or was built-in.</param>
        /// <param name="port">The port to be used. Defaults to 465 for TLS based connections, 587 for STARTTLS based connections and port 25 for insecure plain-text connections..</param>
        /// <param name="server">The address of the SMTP server..</param>
        /// <param name="username">Username for SMTP authentication.</param>
        public GetClusterNotificationsEndpointsSmtp200ResponseDataInner(string author = default(string), string comment = default(string), Int64 disable = default(Int64), string fromAddress = default(string), List<string> mailto = default(List<string>), List<string> mailtoUser = default(List<string>), string mode = default(string), string name = default(string), string origin = default(string), Int64 port = default(Int64), string server = default(string), string username = default(string))
        {
            this.Author = author;
            this.Comment = comment;
            this.Disable = disable;
            this.FromAddress = fromAddress;
            this.Mailto = mailto;
            this.MailtoUser = mailtoUser;
            this.Mode = mode;
            this.Name = name;
            this.Origin = origin;
            this.Port = port;
            this.Server = server;
            this.Username = username;
        }

        /// <summary>
        /// Author of the mail. Defaults to &#39;Proxmox VE&#39;.
        /// </summary>
        /// <value>Author of the mail. Defaults to &#39;Proxmox VE&#39;.</value>
        [DataMember(Name = "author", EmitDefaultValue = false)]
        public string Author { get; set; }

        /// <summary>
        /// Comment
        /// </summary>
        /// <value>Comment</value>
        [DataMember(Name = "comment", EmitDefaultValue = false)]
        public string Comment { get; set; }

        /// <summary>
        /// Disable this target
        /// </summary>
        /// <value>Disable this target</value>
        [DataMember(Name = "disable", EmitDefaultValue = false)]
        public Int64 Disable { get; set; }

        /// <summary>
        /// &#x60;From&#x60; address for the mail
        /// </summary>
        /// <value>&#x60;From&#x60; address for the mail</value>
        [DataMember(Name = "from-address", EmitDefaultValue = false)]
        public string FromAddress { get; set; }

        /// <summary>
        /// List of email recipients
        /// </summary>
        /// <value>List of email recipients</value>
        [DataMember(Name = "mailto", EmitDefaultValue = false)]
        public List<string> Mailto { get; set; }

        /// <summary>
        /// List of users
        /// </summary>
        /// <value>List of users</value>
        [DataMember(Name = "mailto-user", EmitDefaultValue = false)]
        public List<string> MailtoUser { get; set; }

        /// <summary>
        /// Determine which encryption method shall be used for the connection.
        /// </summary>
        /// <value>Determine which encryption method shall be used for the connection.</value>
        [DataMember(Name = "mode", EmitDefaultValue = false)]
        public string Mode { get; set; }

        /// <summary>
        /// The name of the endpoint.
        /// </summary>
        /// <value>The name of the endpoint.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Show if this entry was created by a user or was built-in
        /// </summary>
        /// <value>Show if this entry was created by a user or was built-in</value>
        [DataMember(Name = "origin", EmitDefaultValue = false)]
        public string Origin { get; set; }

        /// <summary>
        /// The port to be used. Defaults to 465 for TLS based connections, 587 for STARTTLS based connections and port 25 for insecure plain-text connections.
        /// </summary>
        /// <value>The port to be used. Defaults to 465 for TLS based connections, 587 for STARTTLS based connections and port 25 for insecure plain-text connections.</value>
        [DataMember(Name = "port", EmitDefaultValue = false)]
        public Int64 Port { get; set; }

        /// <summary>
        /// The address of the SMTP server.
        /// </summary>
        /// <value>The address of the SMTP server.</value>
        [DataMember(Name = "server", EmitDefaultValue = false)]
        public string Server { get; set; }

        /// <summary>
        /// Username for SMTP authentication
        /// </summary>
        /// <value>Username for SMTP authentication</value>
        [DataMember(Name = "username", EmitDefaultValue = false)]
        public string Username { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetClusterNotificationsEndpointsSmtp200ResponseDataInner {\n");
            sb.Append("  Author: ").Append(Author).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  Disable: ").Append(Disable).Append("\n");
            sb.Append("  FromAddress: ").Append(FromAddress).Append("\n");
            sb.Append("  Mailto: ").Append(Mailto).Append("\n");
            sb.Append("  MailtoUser: ").Append(MailtoUser).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Origin: ").Append(Origin).Append("\n");
            sb.Append("  Port: ").Append(Port).Append("\n");
            sb.Append("  Server: ").Append(Server).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
