/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetClusterNotificationsEndpointsWebhook200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getClusterNotificationsEndpointsWebhook_200_response_data_inner")]
    public partial class GetClusterNotificationsEndpointsWebhook200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetClusterNotificationsEndpointsWebhook200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="body">HTTP body, base64 encoded.</param>
        /// <param name="comment">Comment.</param>
        /// <param name="disable">Disable this target.</param>
        /// <param name="header">HTTP headers to set. These have to be formatted as a property string in the format name&#x3D;&lt;name&gt;,value&#x3D;&lt;base64 of value&gt;.</param>
        /// <param name="method">HTTP method.</param>
        /// <param name="name">The name of the endpoint..</param>
        /// <param name="origin">Show if this entry was created by a user or was built-in.</param>
        /// <param name="secret">Secrets to set. These have to be formatted as a property string in the format name&#x3D;&lt;name&gt;,value&#x3D;&lt;base64 of value&gt;.</param>
        /// <param name="url">Server URL.</param>
        public GetClusterNotificationsEndpointsWebhook200ResponseDataInner(string body = default(string), string comment = default(string), Int64 disable = default(Int64), List<string> header = default(List<string>), string method = default(string), string name = default(string), string origin = default(string), List<string> secret = default(List<string>), string url = default(string))
        {
            this.Body = body;
            this.Comment = comment;
            this.Disable = disable;
            this.Header = header;
            this.Method = method;
            this.Name = name;
            this.Origin = origin;
            this.Secret = secret;
            this.Url = url;
        }

        /// <summary>
        /// HTTP body, base64 encoded
        /// </summary>
        /// <value>HTTP body, base64 encoded</value>
        [DataMember(Name = "body", EmitDefaultValue = false)]
        public string Body { get; set; }

        /// <summary>
        /// Comment
        /// </summary>
        /// <value>Comment</value>
        [DataMember(Name = "comment", EmitDefaultValue = false)]
        public string Comment { get; set; }

        /// <summary>
        /// Disable this target
        /// </summary>
        /// <value>Disable this target</value>
        [DataMember(Name = "disable", EmitDefaultValue = false)]
        public Int64 Disable { get; set; }

        /// <summary>
        /// HTTP headers to set. These have to be formatted as a property string in the format name&#x3D;&lt;name&gt;,value&#x3D;&lt;base64 of value&gt;
        /// </summary>
        /// <value>HTTP headers to set. These have to be formatted as a property string in the format name&#x3D;&lt;name&gt;,value&#x3D;&lt;base64 of value&gt;</value>
        [DataMember(Name = "header", EmitDefaultValue = false)]
        public List<string> Header { get; set; }

        /// <summary>
        /// HTTP method
        /// </summary>
        /// <value>HTTP method</value>
        [DataMember(Name = "method", EmitDefaultValue = false)]
        public string Method { get; set; }

        /// <summary>
        /// The name of the endpoint.
        /// </summary>
        /// <value>The name of the endpoint.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Show if this entry was created by a user or was built-in
        /// </summary>
        /// <value>Show if this entry was created by a user or was built-in</value>
        [DataMember(Name = "origin", EmitDefaultValue = false)]
        public string Origin { get; set; }

        /// <summary>
        /// Secrets to set. These have to be formatted as a property string in the format name&#x3D;&lt;name&gt;,value&#x3D;&lt;base64 of value&gt;
        /// </summary>
        /// <value>Secrets to set. These have to be formatted as a property string in the format name&#x3D;&lt;name&gt;,value&#x3D;&lt;base64 of value&gt;</value>
        [DataMember(Name = "secret", EmitDefaultValue = false)]
        public List<string> Secret { get; set; }

        /// <summary>
        /// Server URL
        /// </summary>
        /// <value>Server URL</value>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetClusterNotificationsEndpointsWebhook200ResponseDataInner {\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  Disable: ").Append(Disable).Append("\n");
            sb.Append("  Header: ").Append(Header).Append("\n");
            sb.Append("  Method: ").Append(Method).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Origin: ").Append(Origin).Append("\n");
            sb.Append("  Secret: ").Append(Secret).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
