/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// Items for each type of service containing objects for each instance.
    /// </summary>
    [DataContract(Name = "getClusterCephMetadata_200_response_data")]
    public partial class GetClusterCephMetadata200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetClusterCephMetadata200ResponseData" /> class.
        /// </summary>
        /// <param name="mds">mds.</param>
        /// <param name="mgr">mgr.</param>
        /// <param name="mon">mon.</param>
        /// <param name="node">node.</param>
        /// <param name="osd">OSDs configured in the cluster and their properties..</param>
        public GetClusterCephMetadata200ResponseData(GetClusterCephMetadata200ResponseDataMds mds = default(GetClusterCephMetadata200ResponseDataMds), GetClusterCephMetadata200ResponseDataMgr mgr = default(GetClusterCephMetadata200ResponseDataMgr), GetClusterCephMetadata200ResponseDataMon mon = default(GetClusterCephMetadata200ResponseDataMon), GetClusterCephMetadata200ResponseDataNode node = default(GetClusterCephMetadata200ResponseDataNode), List<string> osd = default(List<string>))
        {
            this.Mds = mds;
            this.Mgr = mgr;
            this.Mon = mon;
            this.Node = node;
            this.Osd = osd;
        }

        /// <summary>
        /// Gets or Sets Mds
        /// </summary>
        [DataMember(Name = "mds", EmitDefaultValue = false)]
        public GetClusterCephMetadata200ResponseDataMds Mds { get; set; }

        /// <summary>
        /// Gets or Sets Mgr
        /// </summary>
        [DataMember(Name = "mgr", EmitDefaultValue = false)]
        public GetClusterCephMetadata200ResponseDataMgr Mgr { get; set; }

        /// <summary>
        /// Gets or Sets Mon
        /// </summary>
        [DataMember(Name = "mon", EmitDefaultValue = false)]
        public GetClusterCephMetadata200ResponseDataMon Mon { get; set; }

        /// <summary>
        /// Gets or Sets Node
        /// </summary>
        [DataMember(Name = "node", EmitDefaultValue = false)]
        public GetClusterCephMetadata200ResponseDataNode Node { get; set; }

        /// <summary>
        /// OSDs configured in the cluster and their properties.
        /// </summary>
        /// <value>OSDs configured in the cluster and their properties.</value>
        [DataMember(Name = "osd", EmitDefaultValue = false)]
        public List<string> Osd { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetClusterCephMetadata200ResponseData {\n");
            sb.Append("  Mds: ").Append(Mds).Append("\n");
            sb.Append("  Mgr: ").Append(Mgr).Append("\n");
            sb.Append("  Mon: ").Append(Mon).Append("\n");
            sb.Append("  Node: ").Append(Node).Append("\n");
            sb.Append("  Osd: ").Append(Osd).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
