/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetClusterNotificationsTargets200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getClusterNotificationsTargets_200_response_data_inner")]
    public partial class GetClusterNotificationsTargets200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetClusterNotificationsTargets200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="comment">Comment.</param>
        /// <param name="disable">Show if this target is disabled.</param>
        /// <param name="name">Name of the target..</param>
        /// <param name="origin">Show if this entry was created by a user or was built-in.</param>
        /// <param name="type">Type of the target..</param>
        public GetClusterNotificationsTargets200ResponseDataInner(string comment = default(string), Int64 disable = default(Int64), string name = default(string), string origin = default(string), string type = default(string))
        {
            this.Comment = comment;
            this.Disable = disable;
            this.Name = name;
            this.Origin = origin;
            this.Type = type;
        }

        /// <summary>
        /// Comment
        /// </summary>
        /// <value>Comment</value>
        [DataMember(Name = "comment", EmitDefaultValue = false)]
        public string Comment { get; set; }

        /// <summary>
        /// Show if this target is disabled
        /// </summary>
        /// <value>Show if this target is disabled</value>
        [DataMember(Name = "disable", EmitDefaultValue = false)]
        public Int64 Disable { get; set; }

        /// <summary>
        /// Name of the target.
        /// </summary>
        /// <value>Name of the target.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Show if this entry was created by a user or was built-in
        /// </summary>
        /// <value>Show if this entry was created by a user or was built-in</value>
        [DataMember(Name = "origin", EmitDefaultValue = false)]
        public string Origin { get; set; }

        /// <summary>
        /// Type of the target.
        /// </summary>
        /// <value>Type of the target.</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetClusterNotificationsTargets200ResponseDataInner {\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  Disable: ").Append(Disable).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Origin: ").Append(Origin).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
