/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetClusterCephMetadata200ResponseDataNodeNode
    /// </summary>
    [DataContract(Name = "getClusterCephMetadata_200_response_data_node__node_")]
    public partial class GetClusterCephMetadata200ResponseDataNodeNode : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetClusterCephMetadata200ResponseDataNodeNode" /> class.
        /// </summary>
        /// <param name="buildcommit">GIT commit used for the build..</param>
        /// <param name="varVersion">varVersion.</param>
        public GetClusterCephMetadata200ResponseDataNodeNode(string buildcommit = default(string), GetClusterCephMetadata200ResponseDataNodeNodeVersion varVersion = default(GetClusterCephMetadata200ResponseDataNodeNodeVersion))
        {
            this.Buildcommit = buildcommit;
            this.VarVersion = varVersion;
        }

        /// <summary>
        /// GIT commit used for the build.
        /// </summary>
        /// <value>GIT commit used for the build.</value>
        [DataMember(Name = "buildcommit", EmitDefaultValue = false)]
        public string Buildcommit { get; set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [DataMember(Name = "version", EmitDefaultValue = false)]
        public GetClusterCephMetadata200ResponseDataNodeNodeVersion VarVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetClusterCephMetadata200ResponseDataNodeNode {\n");
            sb.Append("  Buildcommit: ").Append(Buildcommit).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
