/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetClusterMappingPci200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getClusterMappingPci_200_response_data_inner")]
    public partial class GetClusterMappingPci200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetClusterMappingPci200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="checks">A list of checks, only present if &#39;check_node&#39; is set..</param>
        /// <param name="description">A description of the logical mapping..</param>
        /// <param name="id">The logical ID of the mapping..</param>
        /// <param name="map">The entries of the mapping..</param>
        public GetClusterMappingPci200ResponseDataInner(List<GetClusterMappingDir200ResponseDataInnerChecksInner> checks = default(List<GetClusterMappingDir200ResponseDataInnerChecksInner>), string description = default(string), string id = default(string), List<string> map = default(List<string>))
        {
            this.Checks = checks;
            this.Description = description;
            this.Id = id;
            this.Map = map;
        }

        /// <summary>
        /// A list of checks, only present if &#39;check_node&#39; is set.
        /// </summary>
        /// <value>A list of checks, only present if &#39;check_node&#39; is set.</value>
        [DataMember(Name = "checks", EmitDefaultValue = false)]
        public List<GetClusterMappingDir200ResponseDataInnerChecksInner> Checks { get; set; }

        /// <summary>
        /// A description of the logical mapping.
        /// </summary>
        /// <value>A description of the logical mapping.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// The logical ID of the mapping.
        /// </summary>
        /// <value>The logical ID of the mapping.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// The entries of the mapping.
        /// </summary>
        /// <value>The entries of the mapping.</value>
        [DataMember(Name = "map", EmitDefaultValue = false)]
        public List<string> Map { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetClusterMappingPci200ResponseDataInner {\n");
            sb.Append("  Checks: ").Append(Checks).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Map: ").Append(Map).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
