/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetNodesSingleDisksLvm200ResponseData
    /// </summary>
    [DataContract(Name = "getNodesSingleDisksLvm_200_response_data")]
    public partial class GetNodesSingleDisksLvm200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodesSingleDisksLvm200ResponseData" /> class.
        /// </summary>
        /// <param name="children">children.</param>
        /// <param name="leaf">leaf.</param>
        public GetNodesSingleDisksLvm200ResponseData(List<GetNodesSingleDisksLvm200ResponseDataChildrenInner> children = default(List<GetNodesSingleDisksLvm200ResponseDataChildrenInner>), Int64 leaf = default(Int64))
        {
            this.Children = children;
            this.Leaf = leaf;
        }

        /// <summary>
        /// Gets or Sets Children
        /// </summary>
        [DataMember(Name = "children", EmitDefaultValue = false)]
        public List<GetNodesSingleDisksLvm200ResponseDataChildrenInner> Children { get; set; }

        /// <summary>
        /// Gets or Sets Leaf
        /// </summary>
        [DataMember(Name = "leaf", EmitDefaultValue = false)]
        public Int64 Leaf { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodesSingleDisksLvm200ResponseData {\n");
            sb.Append("  Children: ").Append(Children).Append("\n");
            sb.Append("  Leaf: ").Append(Leaf).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
