/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// List of not allowed nodes with additional information.
    /// </summary>
    [DataContract(Name = "getNodesSingleLxcSingleMigrate_200_response_data_not_allowed_nodes")]
    public partial class GetNodesSingleLxcSingleMigrate200ResponseDataNotAllowedNodes : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodesSingleLxcSingleMigrate200ResponseDataNotAllowedNodes" /> class.
        /// </summary>
        /// <param name="blockingHaResources">HA resources, which are blocking the container from being migrated to the node..</param>
        public GetNodesSingleLxcSingleMigrate200ResponseDataNotAllowedNodes(List<CreateClusterHaResourcesSingleMigrate200ResponseDataBlockingResourcesInner> blockingHaResources = default(List<CreateClusterHaResourcesSingleMigrate200ResponseDataBlockingResourcesInner>))
        {
            this.BlockingHaResources = blockingHaResources;
        }

        /// <summary>
        /// HA resources, which are blocking the container from being migrated to the node.
        /// </summary>
        /// <value>HA resources, which are blocking the container from being migrated to the node.</value>
        [DataMember(Name = "blocking-ha-resources", EmitDefaultValue = false)]
        public List<CreateClusterHaResourcesSingleMigrate200ResponseDataBlockingResourcesInner> BlockingHaResources { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodesSingleLxcSingleMigrate200ResponseDataNotAllowedNodes {\n");
            sb.Append("  BlockingHaResources: ").Append(BlockingHaResources).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
