/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetNodesSingleStatus200ResponseDataCpuinfo
    /// </summary>
    [DataContract(Name = "getNodesSingleStatus_200_response_data_cpuinfo")]
    public partial class GetNodesSingleStatus200ResponseDataCpuinfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodesSingleStatus200ResponseDataCpuinfo" /> class.
        /// </summary>
        /// <param name="cores">The number of physical cores of the CPU..</param>
        /// <param name="cpus">The number of logical threads of the CPU..</param>
        /// <param name="model">The CPU model.</param>
        /// <param name="sockets">The number of logical threads of the CPU..</param>
        public GetNodesSingleStatus200ResponseDataCpuinfo(Int64 cores = default(Int64), Int64 cpus = default(Int64), string model = default(string), Int64 sockets = default(Int64))
        {
            this.Cores = cores;
            this.Cpus = cpus;
            this.Model = model;
            this.Sockets = sockets;
        }

        /// <summary>
        /// The number of physical cores of the CPU.
        /// </summary>
        /// <value>The number of physical cores of the CPU.</value>
        [DataMember(Name = "cores", EmitDefaultValue = false)]
        public Int64 Cores { get; set; }

        /// <summary>
        /// The number of logical threads of the CPU.
        /// </summary>
        /// <value>The number of logical threads of the CPU.</value>
        [DataMember(Name = "cpus", EmitDefaultValue = false)]
        public Int64 Cpus { get; set; }

        /// <summary>
        /// The CPU model
        /// </summary>
        /// <value>The CPU model</value>
        [DataMember(Name = "model", EmitDefaultValue = false)]
        public string Model { get; set; }

        /// <summary>
        /// The number of logical threads of the CPU.
        /// </summary>
        /// <value>The number of logical threads of the CPU.</value>
        [DataMember(Name = "sockets", EmitDefaultValue = false)]
        public Int64 Sockets { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodesSingleStatus200ResponseDataCpuinfo {\n");
            sb.Append("  Cores: ").Append(Cores).Append("\n");
            sb.Append("  Cpus: ").Append(Cpus).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  Sockets: ").Append(Sockets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
