/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetNodesSingleCephOsdSingleLvinfo200ResponseData
    /// </summary>
    [DataContract(Name = "getNodesSingleCephOsdSingleLvinfo_200_response_data")]
    public partial class GetNodesSingleCephOsdSingleLvinfo200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodesSingleCephOsdSingleLvinfo200ResponseData" /> class.
        /// </summary>
        /// <param name="creationTime">Creation time as reported by &#x60;lvs&#x60;..</param>
        /// <param name="lvName">Name of the logical volume (LV)..</param>
        /// <param name="lvPath">Path to the logical volume (LV)..</param>
        /// <param name="lvSize">Size of the logical volume (LV)..</param>
        /// <param name="lvUuid">UUID of the logical volume (LV)..</param>
        /// <param name="vgName">Name of the volume group (VG)..</param>
        public GetNodesSingleCephOsdSingleLvinfo200ResponseData(string creationTime = default(string), string lvName = default(string), string lvPath = default(string), Int64 lvSize = default(Int64), string lvUuid = default(string), string vgName = default(string))
        {
            this.CreationTime = creationTime;
            this.LvName = lvName;
            this.LvPath = lvPath;
            this.LvSize = lvSize;
            this.LvUuid = lvUuid;
            this.VgName = vgName;
        }

        /// <summary>
        /// Creation time as reported by &#x60;lvs&#x60;.
        /// </summary>
        /// <value>Creation time as reported by &#x60;lvs&#x60;.</value>
        [DataMember(Name = "creation_time", EmitDefaultValue = false)]
        public string CreationTime { get; set; }

        /// <summary>
        /// Name of the logical volume (LV).
        /// </summary>
        /// <value>Name of the logical volume (LV).</value>
        [DataMember(Name = "lv_name", EmitDefaultValue = false)]
        public string LvName { get; set; }

        /// <summary>
        /// Path to the logical volume (LV).
        /// </summary>
        /// <value>Path to the logical volume (LV).</value>
        [DataMember(Name = "lv_path", EmitDefaultValue = false)]
        public string LvPath { get; set; }

        /// <summary>
        /// Size of the logical volume (LV).
        /// </summary>
        /// <value>Size of the logical volume (LV).</value>
        [DataMember(Name = "lv_size", EmitDefaultValue = false)]
        public Int64 LvSize { get; set; }

        /// <summary>
        /// UUID of the logical volume (LV).
        /// </summary>
        /// <value>UUID of the logical volume (LV).</value>
        [DataMember(Name = "lv_uuid", EmitDefaultValue = false)]
        public string LvUuid { get; set; }

        /// <summary>
        /// Name of the volume group (VG).
        /// </summary>
        /// <value>Name of the volume group (VG).</value>
        [DataMember(Name = "vg_name", EmitDefaultValue = false)]
        public string VgName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodesSingleCephOsdSingleLvinfo200ResponseData {\n");
            sb.Append("  CreationTime: ").Append(CreationTime).Append("\n");
            sb.Append("  LvName: ").Append(LvName).Append("\n");
            sb.Append("  LvPath: ").Append(LvPath).Append("\n");
            sb.Append("  LvSize: ").Append(LvSize).Append("\n");
            sb.Append("  LvUuid: ").Append(LvUuid).Append("\n");
            sb.Append("  VgName: ").Append(VgName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
