/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// Last backup verification result, only useful for PBS storages.
    /// </summary>
    [DataContract(Name = "getNodesSingleStorageSingleContent_200_response_data_inner_verification")]
    public partial class GetNodesSingleStorageSingleContent200ResponseDataInnerVerification : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodesSingleStorageSingleContent200ResponseDataInnerVerification" /> class.
        /// </summary>
        /// <param name="state">Last backup verification state..</param>
        /// <param name="upid">Last backup verification UPID..</param>
        public GetNodesSingleStorageSingleContent200ResponseDataInnerVerification(string state = default(string), string upid = default(string))
        {
            this.State = state;
            this.Upid = upid;
        }

        /// <summary>
        /// Last backup verification state.
        /// </summary>
        /// <value>Last backup verification state.</value>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public string State { get; set; }

        /// <summary>
        /// Last backup verification UPID.
        /// </summary>
        /// <value>Last backup verification UPID.</value>
        [DataMember(Name = "upid", EmitDefaultValue = false)]
        public string Upid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodesSingleStorageSingleContent200ResponseDataInnerVerification {\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Upid: ").Append(Upid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
