/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// Meta-information about the boot mode.
    /// </summary>
    [DataContract(Name = "getNodesSingleStatus_200_response_data_boot_info")]
    public partial class GetNodesSingleStatus200ResponseDataBootInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodesSingleStatus200ResponseDataBootInfo" /> class.
        /// </summary>
        /// <param name="mode">Through which firmware the system got booted..</param>
        /// <param name="secureboot">System is booted in secure mode, only applicable for the \&quot;efi\&quot; mode..</param>
        public GetNodesSingleStatus200ResponseDataBootInfo(string mode = default(string), Int64 secureboot = default(Int64))
        {
            this.Mode = mode;
            this.Secureboot = secureboot;
        }

        /// <summary>
        /// Through which firmware the system got booted.
        /// </summary>
        /// <value>Through which firmware the system got booted.</value>
        [DataMember(Name = "mode", EmitDefaultValue = false)]
        public string Mode { get; set; }

        /// <summary>
        /// System is booted in secure mode, only applicable for the \&quot;efi\&quot; mode.
        /// </summary>
        /// <value>System is booted in secure mode, only applicable for the \&quot;efi\&quot; mode.</value>
        [DataMember(Name = "secureboot", EmitDefaultValue = false)]
        public Int64 Secureboot { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodesSingleStatus200ResponseDataBootInfo {\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("  Secureboot: ").Append(Secureboot).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
