/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetNodesSingleAptUpdate200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getNodesSingleAptUpdate_200_response_data_inner")]
    public partial class GetNodesSingleAptUpdate200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodesSingleAptUpdate200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="arch">Package Architecture..</param>
        /// <param name="description">Package description..</param>
        /// <param name="notifyStatus">Version for which PVE has already sent an update notification for..</param>
        /// <param name="oldVersion">Old version currently installed..</param>
        /// <param name="origin">Package origin, e.g., &#39;Proxmox&#39; or &#39;Debian&#39;..</param>
        /// <param name="package">Package name..</param>
        /// <param name="priority">Package priority..</param>
        /// <param name="section">Package section..</param>
        /// <param name="title">Package title..</param>
        /// <param name="varVersion">New version to be updated to..</param>
        public GetNodesSingleAptUpdate200ResponseDataInner(string arch = default(string), string description = default(string), string notifyStatus = default(string), string oldVersion = default(string), string origin = default(string), string package = default(string), string priority = default(string), string section = default(string), string title = default(string), string varVersion = default(string))
        {
            this.Arch = arch;
            this.Description = description;
            this.NotifyStatus = notifyStatus;
            this.OldVersion = oldVersion;
            this.Origin = origin;
            this.Package = package;
            this.Priority = priority;
            this.Section = section;
            this.Title = title;
            this.VarVersion = varVersion;
        }

        /// <summary>
        /// Package Architecture.
        /// </summary>
        /// <value>Package Architecture.</value>
        [DataMember(Name = "Arch", EmitDefaultValue = false)]
        public string Arch { get; set; }

        /// <summary>
        /// Package description.
        /// </summary>
        /// <value>Package description.</value>
        [DataMember(Name = "Description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Version for which PVE has already sent an update notification for.
        /// </summary>
        /// <value>Version for which PVE has already sent an update notification for.</value>
        [DataMember(Name = "NotifyStatus", EmitDefaultValue = false)]
        public string NotifyStatus { get; set; }

        /// <summary>
        /// Old version currently installed.
        /// </summary>
        /// <value>Old version currently installed.</value>
        [DataMember(Name = "OldVersion", EmitDefaultValue = false)]
        public string OldVersion { get; set; }

        /// <summary>
        /// Package origin, e.g., &#39;Proxmox&#39; or &#39;Debian&#39;.
        /// </summary>
        /// <value>Package origin, e.g., &#39;Proxmox&#39; or &#39;Debian&#39;.</value>
        [DataMember(Name = "Origin", EmitDefaultValue = false)]
        public string Origin { get; set; }

        /// <summary>
        /// Package name.
        /// </summary>
        /// <value>Package name.</value>
        [DataMember(Name = "Package", EmitDefaultValue = false)]
        public string Package { get; set; }

        /// <summary>
        /// Package priority.
        /// </summary>
        /// <value>Package priority.</value>
        [DataMember(Name = "Priority", EmitDefaultValue = false)]
        public string Priority { get; set; }

        /// <summary>
        /// Package section.
        /// </summary>
        /// <value>Package section.</value>
        [DataMember(Name = "Section", EmitDefaultValue = false)]
        public string Section { get; set; }

        /// <summary>
        /// Package title.
        /// </summary>
        /// <value>Package title.</value>
        [DataMember(Name = "Title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// New version to be updated to.
        /// </summary>
        /// <value>New version to be updated to.</value>
        [DataMember(Name = "Version", EmitDefaultValue = false)]
        public string VarVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodesSingleAptUpdate200ResponseDataInner {\n");
            sb.Append("  Arch: ").Append(Arch).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  NotifyStatus: ").Append(NotifyStatus).Append("\n");
            sb.Append("  OldVersion: ").Append(OldVersion).Append("\n");
            sb.Append("  Origin: ").Append(Origin).Append("\n");
            sb.Append("  Package: ").Append(Package).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  Section: ").Append(Section).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
