/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetNodesSingleAptRepositories200ResponseDataFilesInnerRepositoriesInner
    /// </summary>
    [DataContract(Name = "getNodesSingleAptRepositories_200_response_data_files_inner_repositories_inner")]
    public partial class GetNodesSingleAptRepositories200ResponseDataFilesInnerRepositoriesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodesSingleAptRepositories200ResponseDataFilesInnerRepositoriesInner" /> class.
        /// </summary>
        /// <param name="comment">Associated comment.</param>
        /// <param name="components">List of repository components.</param>
        /// <param name="enabled">Whether the repository is enabled or not.</param>
        /// <param name="fileType">Format of the defining file..</param>
        /// <param name="options">Additional options.</param>
        /// <param name="suites">List of package distribuitions.</param>
        /// <param name="types">List of package types..</param>
        /// <param name="uRIs">List of repository URIs..</param>
        public GetNodesSingleAptRepositories200ResponseDataFilesInnerRepositoriesInner(string comment = default(string), List<string> components = default(List<string>), Int64 enabled = default(Int64), string fileType = default(string), List<GetNodesSingleAptRepositories200ResponseDataFilesInnerRepositoriesInnerOptionsInner> options = default(List<GetNodesSingleAptRepositories200ResponseDataFilesInnerRepositoriesInnerOptionsInner>), List<string> suites = default(List<string>), List<string> types = default(List<string>), List<string> uRIs = default(List<string>))
        {
            this.Comment = comment;
            this.Components = components;
            this.Enabled = enabled;
            this.FileType = fileType;
            this.Options = options;
            this.Suites = suites;
            this.Types = types;
            this.URIs = uRIs;
        }

        /// <summary>
        /// Associated comment
        /// </summary>
        /// <value>Associated comment</value>
        [DataMember(Name = "Comment", EmitDefaultValue = false)]
        public string Comment { get; set; }

        /// <summary>
        /// List of repository components
        /// </summary>
        /// <value>List of repository components</value>
        [DataMember(Name = "Components", EmitDefaultValue = false)]
        public List<string> Components { get; set; }

        /// <summary>
        /// Whether the repository is enabled or not
        /// </summary>
        /// <value>Whether the repository is enabled or not</value>
        [DataMember(Name = "Enabled", EmitDefaultValue = false)]
        public Int64 Enabled { get; set; }

        /// <summary>
        /// Format of the defining file.
        /// </summary>
        /// <value>Format of the defining file.</value>
        [DataMember(Name = "FileType", EmitDefaultValue = false)]
        public string FileType { get; set; }

        /// <summary>
        /// Additional options
        /// </summary>
        /// <value>Additional options</value>
        [DataMember(Name = "Options", EmitDefaultValue = false)]
        public List<GetNodesSingleAptRepositories200ResponseDataFilesInnerRepositoriesInnerOptionsInner> Options { get; set; }

        /// <summary>
        /// List of package distribuitions
        /// </summary>
        /// <value>List of package distribuitions</value>
        [DataMember(Name = "Suites", EmitDefaultValue = false)]
        public List<string> Suites { get; set; }

        /// <summary>
        /// List of package types.
        /// </summary>
        /// <value>List of package types.</value>
        [DataMember(Name = "Types", EmitDefaultValue = false)]
        public List<string> Types { get; set; }

        /// <summary>
        /// List of repository URIs.
        /// </summary>
        /// <value>List of repository URIs.</value>
        [DataMember(Name = "URIs", EmitDefaultValue = false)]
        public List<string> URIs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodesSingleAptRepositories200ResponseDataFilesInnerRepositoriesInner {\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  Components: ").Append(Components).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  FileType: ").Append(FileType).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("  Suites: ").Append(Suites).Append("\n");
            sb.Append("  Types: ").Append(Types).Append("\n");
            sb.Append("  URIs: ").Append(URIs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
