/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetNodesSingleStorageSingleFilerestoreList200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getNodesSingleStorageSingleFilerestoreList_200_response_data_inner")]
    public partial class GetNodesSingleStorageSingleFilerestoreList200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodesSingleStorageSingleFilerestoreList200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="filepath">base64 path of the current entry.</param>
        /// <param name="leaf">If this entry is a leaf in the directory graph..</param>
        /// <param name="mtime">Entry last-modified time (unix timestamp)..</param>
        /// <param name="size">Entry file size..</param>
        /// <param name="text">Entry display text..</param>
        /// <param name="type">Entry type..</param>
        public GetNodesSingleStorageSingleFilerestoreList200ResponseDataInner(string filepath = default(string), Int64 leaf = default(Int64), Int64 mtime = default(Int64), Int64 size = default(Int64), string text = default(string), string type = default(string))
        {
            this.Filepath = filepath;
            this.Leaf = leaf;
            this.Mtime = mtime;
            this.Size = size;
            this.Text = text;
            this.Type = type;
        }

        /// <summary>
        /// base64 path of the current entry
        /// </summary>
        /// <value>base64 path of the current entry</value>
        [DataMember(Name = "filepath", EmitDefaultValue = false)]
        public string Filepath { get; set; }

        /// <summary>
        /// If this entry is a leaf in the directory graph.
        /// </summary>
        /// <value>If this entry is a leaf in the directory graph.</value>
        [DataMember(Name = "leaf", EmitDefaultValue = false)]
        public Int64 Leaf { get; set; }

        /// <summary>
        /// Entry last-modified time (unix timestamp).
        /// </summary>
        /// <value>Entry last-modified time (unix timestamp).</value>
        [DataMember(Name = "mtime", EmitDefaultValue = false)]
        public Int64 Mtime { get; set; }

        /// <summary>
        /// Entry file size.
        /// </summary>
        /// <value>Entry file size.</value>
        [DataMember(Name = "size", EmitDefaultValue = false)]
        public Int64 Size { get; set; }

        /// <summary>
        /// Entry display text.
        /// </summary>
        /// <value>Entry display text.</value>
        [DataMember(Name = "text", EmitDefaultValue = false)]
        public string Text { get; set; }

        /// <summary>
        /// Entry type.
        /// </summary>
        /// <value>Entry type.</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodesSingleStorageSingleFilerestoreList200ResponseDataInner {\n");
            sb.Append("  Filepath: ").Append(Filepath).Append("\n");
            sb.Append("  Leaf: ").Append(Leaf).Append("\n");
            sb.Append("  Mtime: ").Append(Mtime).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
