/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetNodesSingleLxcSingleInterfaces200ResponseDataInnerIpAddressesInner
    /// </summary>
    [DataContract(Name = "getNodesSingleLxcSingleInterfaces_200_response_data_inner_ip_addresses_inner")]
    public partial class GetNodesSingleLxcSingleInterfaces200ResponseDataInnerIpAddressesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodesSingleLxcSingleInterfaces200ResponseDataInnerIpAddressesInner" /> class.
        /// </summary>
        /// <param name="ipAddress">IP-Address.</param>
        /// <param name="ipAddressType">IP-Family.</param>
        /// <param name="prefix">IP-Prefix.</param>
        public GetNodesSingleLxcSingleInterfaces200ResponseDataInnerIpAddressesInner(string ipAddress = default(string), string ipAddressType = default(string), Int64 prefix = default(Int64))
        {
            this.IpAddress = ipAddress;
            this.IpAddressType = ipAddressType;
            this.Prefix = prefix;
        }

        /// <summary>
        /// IP-Address
        /// </summary>
        /// <value>IP-Address</value>
        [DataMember(Name = "ip-address", EmitDefaultValue = false)]
        public string IpAddress { get; set; }

        /// <summary>
        /// IP-Family
        /// </summary>
        /// <value>IP-Family</value>
        [DataMember(Name = "ip-address-type", EmitDefaultValue = false)]
        public string IpAddressType { get; set; }

        /// <summary>
        /// IP-Prefix
        /// </summary>
        /// <value>IP-Prefix</value>
        [DataMember(Name = "prefix", EmitDefaultValue = false)]
        public Int64 Prefix { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodesSingleLxcSingleInterfaces200ResponseDataInnerIpAddressesInner {\n");
            sb.Append("  IpAddress: ").Append(IpAddress).Append("\n");
            sb.Append("  IpAddressType: ").Append(IpAddressType).Append("\n");
            sb.Append("  Prefix: ").Append(Prefix).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
