/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetNodeSDNZoneContent200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getNodeSDNZoneContent_200_response_data_inner")]
    public partial class GetNodeSDNZoneContent200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodeSDNZoneContent200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="status">Status..</param>
        /// <param name="statusmsg">Status details.</param>
        /// <param name="vnet">Vnet identifier..</param>
        public GetNodeSDNZoneContent200ResponseDataInner(string status = default(string), string statusmsg = default(string), string vnet = default(string))
        {
            this.Status = status;
            this.Statusmsg = statusmsg;
            this.Vnet = vnet;
        }

        /// <summary>
        /// Status.
        /// </summary>
        /// <value>Status.</value>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Status details
        /// </summary>
        /// <value>Status details</value>
        [DataMember(Name = "statusmsg", EmitDefaultValue = false)]
        public string Statusmsg { get; set; }

        /// <summary>
        /// Vnet identifier.
        /// </summary>
        /// <value>Vnet identifier.</value>
        [DataMember(Name = "vnet", EmitDefaultValue = false)]
        public string Vnet { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodeSDNZoneContent200ResponseDataInner {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Statusmsg: ").Append(Statusmsg).Append("\n");
            sb.Append("  Vnet: ").Append(Vnet).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
