/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetNodesSingleSdnZonesSingleIpvrf200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getNodesSingleSdnZonesSingleIpvrf_200_response_data_inner")]
    public partial class GetNodesSingleSdnZonesSingleIpvrf200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodesSingleSdnZonesSingleIpvrf200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="ip">The CIDR of the route table entry..</param>
        /// <param name="metric">This route&#39;s metric..</param>
        /// <param name="nexthops">A list of nexthops for the route table entry..</param>
        /// <param name="protocol">The protocol where this route was learned from (e.g. BGP)..</param>
        public GetNodesSingleSdnZonesSingleIpvrf200ResponseDataInner(string ip = default(string), Int64 metric = default(Int64), List<string> nexthops = default(List<string>), string protocol = default(string))
        {
            this.Ip = ip;
            this.Metric = metric;
            this.Nexthops = nexthops;
            this.Protocol = protocol;
        }

        /// <summary>
        /// The CIDR of the route table entry.
        /// </summary>
        /// <value>The CIDR of the route table entry.</value>
        [DataMember(Name = "ip", EmitDefaultValue = false)]
        public string Ip { get; set; }

        /// <summary>
        /// This route&#39;s metric.
        /// </summary>
        /// <value>This route&#39;s metric.</value>
        [DataMember(Name = "metric", EmitDefaultValue = false)]
        public Int64 Metric { get; set; }

        /// <summary>
        /// A list of nexthops for the route table entry.
        /// </summary>
        /// <value>A list of nexthops for the route table entry.</value>
        [DataMember(Name = "nexthops", EmitDefaultValue = false)]
        public List<string> Nexthops { get; set; }

        /// <summary>
        /// The protocol where this route was learned from (e.g. BGP).
        /// </summary>
        /// <value>The protocol where this route was learned from (e.g. BGP).</value>
        [DataMember(Name = "protocol", EmitDefaultValue = false)]
        public string Protocol { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodesSingleSdnZonesSingleIpvrf200ResponseDataInner {\n");
            sb.Append("  Ip: ").Append(Ip).Append("\n");
            sb.Append("  Metric: ").Append(Metric).Append("\n");
            sb.Append("  Nexthops: ").Append(Nexthops).Append("\n");
            sb.Append("  Protocol: ").Append(Protocol).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
