/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetNodesSingleLxcSingleMigrate200ResponseData
    /// </summary>
    [DataContract(Name = "getNodesSingleLxcSingleMigrate_200_response_data")]
    public partial class GetNodesSingleLxcSingleMigrate200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodesSingleLxcSingleMigrate200ResponseData" /> class.
        /// </summary>
        /// <param name="allowedNodes">List of nodes allowed for migration..</param>
        /// <param name="dependentHaResources">HA resources, which will be migrated to the same target node as the VM, because these are in positive affinity with the VM..</param>
        /// <param name="notAllowedNodes">notAllowedNodes.</param>
        /// <param name="running">Determines if the container is running..</param>
        public GetNodesSingleLxcSingleMigrate200ResponseData(List<string> allowedNodes = default(List<string>), List<string> dependentHaResources = default(List<string>), GetNodesSingleLxcSingleMigrate200ResponseDataNotAllowedNodes notAllowedNodes = default(GetNodesSingleLxcSingleMigrate200ResponseDataNotAllowedNodes), Int64 running = default(Int64))
        {
            this.AllowedNodes = allowedNodes;
            this.DependentHaResources = dependentHaResources;
            this.NotAllowedNodes = notAllowedNodes;
            this.Running = running;
        }

        /// <summary>
        /// List of nodes allowed for migration.
        /// </summary>
        /// <value>List of nodes allowed for migration.</value>
        [DataMember(Name = "allowed-nodes", EmitDefaultValue = false)]
        public List<string> AllowedNodes { get; set; }

        /// <summary>
        /// HA resources, which will be migrated to the same target node as the VM, because these are in positive affinity with the VM.
        /// </summary>
        /// <value>HA resources, which will be migrated to the same target node as the VM, because these are in positive affinity with the VM.</value>
        [DataMember(Name = "dependent-ha-resources", EmitDefaultValue = false)]
        public List<string> DependentHaResources { get; set; }

        /// <summary>
        /// Gets or Sets NotAllowedNodes
        /// </summary>
        [DataMember(Name = "not-allowed-nodes", EmitDefaultValue = false)]
        public GetNodesSingleLxcSingleMigrate200ResponseDataNotAllowedNodes NotAllowedNodes { get; set; }

        /// <summary>
        /// Determines if the container is running.
        /// </summary>
        /// <value>Determines if the container is running.</value>
        [DataMember(Name = "running", EmitDefaultValue = false)]
        public Int64 Running { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodesSingleLxcSingleMigrate200ResponseData {\n");
            sb.Append("  AllowedNodes: ").Append(AllowedNodes).Append("\n");
            sb.Append("  DependentHaResources: ").Append(DependentHaResources).Append("\n");
            sb.Append("  NotAllowedNodes: ").Append(NotAllowedNodes).Append("\n");
            sb.Append("  Running: ").Append(Running).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
