/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetNodesSingleCephFs200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getNodesSingleCephFs_200_response_data_inner")]
    public partial class GetNodesSingleCephFs200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNodesSingleCephFs200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="dataPool">The name of the data pool..</param>
        /// <param name="metadataPool">The name of the metadata pool..</param>
        /// <param name="name">The ceph filesystem name..</param>
        public GetNodesSingleCephFs200ResponseDataInner(string dataPool = default(string), string metadataPool = default(string), string name = default(string))
        {
            this.DataPool = dataPool;
            this.MetadataPool = metadataPool;
            this.Name = name;
        }

        /// <summary>
        /// The name of the data pool.
        /// </summary>
        /// <value>The name of the data pool.</value>
        [DataMember(Name = "data_pool", EmitDefaultValue = false)]
        public string DataPool { get; set; }

        /// <summary>
        /// The name of the metadata pool.
        /// </summary>
        /// <value>The name of the metadata pool.</value>
        [DataMember(Name = "metadata_pool", EmitDefaultValue = false)]
        public string MetadataPool { get; set; }

        /// <summary>
        /// The ceph filesystem name.
        /// </summary>
        /// <value>The ceph filesystem name.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNodesSingleCephFs200ResponseDataInner {\n");
            sb.Append("  DataPool: ").Append(DataPool).Append("\n");
            sb.Append("  MetadataPool: ").Append(MetadataPool).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
