/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// GetVMSnapshots200ResponseDataInner
    /// </summary>
    [DataContract(Name = "getVMSnapshots_200_response_data_inner")]
    public partial class GetVMSnapshots200ResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetVMSnapshots200ResponseDataInner" /> class.
        /// </summary>
        /// <param name="description">Snapshot description..</param>
        /// <param name="name">Snapshot identifier. Value &#39;current&#39; identifies the current VM..</param>
        /// <param name="parent">Parent snapshot identifier..</param>
        /// <param name="snaptime">Snapshot creation time.</param>
        /// <param name="vmstate">Snapshot includes RAM..</param>
        public GetVMSnapshots200ResponseDataInner(string description = default(string), string name = default(string), string parent = default(string), Int64 snaptime = default(Int64), Int64 vmstate = default(Int64))
        {
            this.Description = description;
            this.Name = name;
            this.Parent = parent;
            this.Snaptime = snaptime;
            this.Vmstate = vmstate;
        }

        /// <summary>
        /// Snapshot description.
        /// </summary>
        /// <value>Snapshot description.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Snapshot identifier. Value &#39;current&#39; identifies the current VM.
        /// </summary>
        /// <value>Snapshot identifier. Value &#39;current&#39; identifies the current VM.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Parent snapshot identifier.
        /// </summary>
        /// <value>Parent snapshot identifier.</value>
        [DataMember(Name = "parent", EmitDefaultValue = false)]
        public string Parent { get; set; }

        /// <summary>
        /// Snapshot creation time
        /// </summary>
        /// <value>Snapshot creation time</value>
        [DataMember(Name = "snaptime", EmitDefaultValue = false)]
        public Int64 Snaptime { get; set; }

        /// <summary>
        /// Snapshot includes RAM.
        /// </summary>
        /// <value>Snapshot includes RAM.</value>
        [DataMember(Name = "vmstate", EmitDefaultValue = false)]
        public Int64 Vmstate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetVMSnapshots200ResponseDataInner {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Parent: ").Append(Parent).Append("\n");
            sb.Append("  Snaptime: ").Append(Snaptime).Append("\n");
            sb.Append("  Vmstate: ").Append(Vmstate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
