/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// UpdateNodesSingleAptRepositoriesRequest
    /// </summary>
    [DataContract(Name = "UpdateNodesSingleAptRepositoriesRequest")]
    public partial class UpdateNodesSingleAptRepositoriesRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateNodesSingleAptRepositoriesRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateNodesSingleAptRepositoriesRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateNodesSingleAptRepositoriesRequest" /> class.
        /// </summary>
        /// <param name="digest">digest.</param>
        /// <param name="handle">handle (required).</param>
        public UpdateNodesSingleAptRepositoriesRequest(string digest = default(string), string handle = default(string))
        {
            // to ensure "handle" is required (not null)
            if (handle == null)
            {
                throw new ArgumentNullException("handle is a required property for UpdateNodesSingleAptRepositoriesRequest and cannot be null");
            }
            this.Handle = handle;
            this.Digest = digest;
        }

        /// <summary>
        /// Gets or Sets Digest
        /// </summary>
        [DataMember(Name = "digest", EmitDefaultValue = false)]
        public string Digest { get; set; }

        /// <summary>
        /// Gets or Sets Handle
        /// </summary>
        [DataMember(Name = "handle", IsRequired = true, EmitDefaultValue = true)]
        public string Handle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateNodesSingleAptRepositoriesRequest {\n");
            sb.Append("  Digest: ").Append(Digest).Append("\n");
            sb.Append("  Handle: ").Append(Handle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
