/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// UpdateClusterSdnFabricsNodeSingleSingleRequest
    /// </summary>
    [DataContract(Name = "UpdateClusterSdnFabricsNodeSingleSingleRequest")]
    public partial class UpdateClusterSdnFabricsNodeSingleSingleRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateClusterSdnFabricsNodeSingleSingleRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateClusterSdnFabricsNodeSingleSingleRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateClusterSdnFabricsNodeSingleSingleRequest" /> class.
        /// </summary>
        /// <param name="delete">delete.</param>
        /// <param name="digest">digest.</param>
        /// <param name="interfaces">interfaces (required).</param>
        /// <param name="ip">ip.</param>
        /// <param name="ip6">ip6.</param>
        /// <param name="lockToken">lockToken.</param>
        /// <param name="protocol">protocol (required).</param>
        public UpdateClusterSdnFabricsNodeSingleSingleRequest(List<string> delete = default(List<string>), string digest = default(string), List<string> interfaces = default(List<string>), string ip = default(string), string ip6 = default(string), string lockToken = default(string), string protocol = default(string))
        {
            // to ensure "interfaces" is required (not null)
            if (interfaces == null)
            {
                throw new ArgumentNullException("interfaces is a required property for UpdateClusterSdnFabricsNodeSingleSingleRequest and cannot be null");
            }
            this.Interfaces = interfaces;
            // to ensure "protocol" is required (not null)
            if (protocol == null)
            {
                throw new ArgumentNullException("protocol is a required property for UpdateClusterSdnFabricsNodeSingleSingleRequest and cannot be null");
            }
            this.Protocol = protocol;
            this.Delete = delete;
            this.Digest = digest;
            this.Ip = ip;
            this.Ip6 = ip6;
            this.LockToken = lockToken;
        }

        /// <summary>
        /// Gets or Sets Delete
        /// </summary>
        [DataMember(Name = "delete", EmitDefaultValue = false)]
        public List<string> Delete { get; set; }

        /// <summary>
        /// Gets or Sets Digest
        /// </summary>
        [DataMember(Name = "digest", EmitDefaultValue = false)]
        public string Digest { get; set; }

        /// <summary>
        /// Gets or Sets Interfaces
        /// </summary>
        [DataMember(Name = "interfaces", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Interfaces { get; set; }

        /// <summary>
        /// Gets or Sets Ip
        /// </summary>
        [DataMember(Name = "ip", EmitDefaultValue = false)]
        public string Ip { get; set; }

        /// <summary>
        /// Gets or Sets Ip6
        /// </summary>
        [DataMember(Name = "ip6", EmitDefaultValue = false)]
        public string Ip6 { get; set; }

        /// <summary>
        /// Gets or Sets LockToken
        /// </summary>
        [DataMember(Name = "lock-token", EmitDefaultValue = false)]
        public string LockToken { get; set; }

        /// <summary>
        /// Gets or Sets Protocol
        /// </summary>
        [DataMember(Name = "protocol", IsRequired = true, EmitDefaultValue = true)]
        public string Protocol { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateClusterSdnFabricsNodeSingleSingleRequest {\n");
            sb.Append("  Delete: ").Append(Delete).Append("\n");
            sb.Append("  Digest: ").Append(Digest).Append("\n");
            sb.Append("  Interfaces: ").Append(Interfaces).Append("\n");
            sb.Append("  Ip: ").Append(Ip).Append("\n");
            sb.Append("  Ip6: ").Append(Ip6).Append("\n");
            sb.Append("  LockToken: ").Append(LockToken).Append("\n");
            sb.Append("  Protocol: ").Append(Protocol).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
