/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// UpdateClusterFirewallOptionsRequest
    /// </summary>
    [DataContract(Name = "UpdateClusterFirewallOptionsRequest")]
    public partial class UpdateClusterFirewallOptionsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateClusterFirewallOptionsRequest" /> class.
        /// </summary>
        /// <param name="delete">delete.</param>
        /// <param name="digest">digest.</param>
        /// <param name="ebtables">ebtables.</param>
        /// <param name="enable">enable.</param>
        /// <param name="logRatelimit">logRatelimit.</param>
        /// <param name="policyForward">policyForward.</param>
        /// <param name="policyIn">policyIn.</param>
        /// <param name="policyOut">policyOut.</param>
        public UpdateClusterFirewallOptionsRequest(string delete = default(string), string digest = default(string), bool ebtables = default(bool), int enable = default(int), string logRatelimit = default(string), string policyForward = default(string), string policyIn = default(string), string policyOut = default(string))
        {
            this.Delete = delete;
            this.Digest = digest;
            this.Ebtables = ebtables;
            this.Enable = enable;
            this.LogRatelimit = logRatelimit;
            this.PolicyForward = policyForward;
            this.PolicyIn = policyIn;
            this.PolicyOut = policyOut;
        }

        /// <summary>
        /// Gets or Sets Delete
        /// </summary>
        [DataMember(Name = "delete", EmitDefaultValue = false)]
        public string Delete { get; set; }

        /// <summary>
        /// Gets or Sets Digest
        /// </summary>
        [DataMember(Name = "digest", EmitDefaultValue = false)]
        public string Digest { get; set; }

        /// <summary>
        /// Gets or Sets Ebtables
        /// </summary>
        [DataMember(Name = "ebtables", EmitDefaultValue = true)]
        public bool Ebtables { get; set; }

        /// <summary>
        /// Gets or Sets Enable
        /// </summary>
        [DataMember(Name = "enable", EmitDefaultValue = false)]
        public int Enable { get; set; }

        /// <summary>
        /// Gets or Sets LogRatelimit
        /// </summary>
        [DataMember(Name = "log_ratelimit", EmitDefaultValue = false)]
        public string LogRatelimit { get; set; }

        /// <summary>
        /// Gets or Sets PolicyForward
        /// </summary>
        [DataMember(Name = "policy_forward", EmitDefaultValue = false)]
        public string PolicyForward { get; set; }

        /// <summary>
        /// Gets or Sets PolicyIn
        /// </summary>
        [DataMember(Name = "policy_in", EmitDefaultValue = false)]
        public string PolicyIn { get; set; }

        /// <summary>
        /// Gets or Sets PolicyOut
        /// </summary>
        [DataMember(Name = "policy_out", EmitDefaultValue = false)]
        public string PolicyOut { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateClusterFirewallOptionsRequest {\n");
            sb.Append("  Delete: ").Append(Delete).Append("\n");
            sb.Append("  Digest: ").Append(Digest).Append("\n");
            sb.Append("  Ebtables: ").Append(Ebtables).Append("\n");
            sb.Append("  Enable: ").Append(Enable).Append("\n");
            sb.Append("  LogRatelimit: ").Append(LogRatelimit).Append("\n");
            sb.Append("  PolicyForward: ").Append(PolicyForward).Append("\n");
            sb.Append("  PolicyIn: ").Append(PolicyIn).Append("\n");
            sb.Append("  PolicyOut: ").Append(PolicyOut).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
