/*
 * ProxMox VE API
 *
 * ProxMox VE API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@lumaserv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ProxmoxSharp.Client.OpenAPIDateConverter;

namespace ProxmoxSharp.Model
{
    /// <summary>
    /// UpdateClusterSdnVnetsSingleFirewallOptionsRequest
    /// </summary>
    [DataContract(Name = "UpdateClusterSdnVnetsSingleFirewallOptionsRequest")]
    public partial class UpdateClusterSdnVnetsSingleFirewallOptionsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateClusterSdnVnetsSingleFirewallOptionsRequest" /> class.
        /// </summary>
        /// <param name="delete">delete.</param>
        /// <param name="digest">digest.</param>
        /// <param name="enable">enable.</param>
        /// <param name="logLevelForward">logLevelForward.</param>
        /// <param name="policyForward">policyForward.</param>
        public UpdateClusterSdnVnetsSingleFirewallOptionsRequest(string delete = default(string), string digest = default(string), bool enable = default(bool), string logLevelForward = default(string), string policyForward = default(string))
        {
            this.Delete = delete;
            this.Digest = digest;
            this.Enable = enable;
            this.LogLevelForward = logLevelForward;
            this.PolicyForward = policyForward;
        }

        /// <summary>
        /// Gets or Sets Delete
        /// </summary>
        [DataMember(Name = "delete", EmitDefaultValue = false)]
        public string Delete { get; set; }

        /// <summary>
        /// Gets or Sets Digest
        /// </summary>
        [DataMember(Name = "digest", EmitDefaultValue = false)]
        public string Digest { get; set; }

        /// <summary>
        /// Gets or Sets Enable
        /// </summary>
        [DataMember(Name = "enable", EmitDefaultValue = true)]
        public bool Enable { get; set; }

        /// <summary>
        /// Gets or Sets LogLevelForward
        /// </summary>
        [DataMember(Name = "log_level_forward", EmitDefaultValue = false)]
        public string LogLevelForward { get; set; }

        /// <summary>
        /// Gets or Sets PolicyForward
        /// </summary>
        [DataMember(Name = "policy_forward", EmitDefaultValue = false)]
        public string PolicyForward { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateClusterSdnVnetsSingleFirewallOptionsRequest {\n");
            sb.Append("  Delete: ").Append(Delete).Append("\n");
            sb.Append("  Digest: ").Append(Digest).Append("\n");
            sb.Append("  Enable: ").Append(Enable).Append("\n");
            sb.Append("  LogLevelForward: ").Append(LogLevelForward).Append("\n");
            sb.Append("  PolicyForward: ").Append(PolicyForward).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
